### ISSUE TITLE
Real debrid doesnt stay connected

### ISSUE THREAD

**Issue by oathzed** [LivingWithHippos/unchained-android#32]
I just authed it a few hours ago, now it just unauthed itself

**Comment by LivingWithHippos** [comment]
Fixed in version 1.6.7-beta

**Comment by Invictaz** [comment]
@LivingWithHippos I still have this in 4.2.5 beta

Yesterday it unauthed itself. I needed to provide the private API token again. By the way which RD says is not safe.
